# .bashrc


export CLICOLOR=1
if [[ $- != *i* ]]; then return;fi

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
#source tmux things
if [ -f ~/.bashrc.d/tmux ];then
	. ~/.bashrc.d/tmux 
fi
#source extra scripts
for f in ~/.bashrc.d/*.sh; do
	. $f
done
xmod
# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
# found in script in ~/.bashrc.d

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
