# .bashrc


if [[ $- != *i* ]]; then return;fi

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
#source tmux things
if [ -f ~/.bashrc.d/tmux ];then
	. ~/.bashrc.d/tmux 
fi
#source extra scripts
for f in ~/.bashrc.d/*.sh; do
	. $f
done
xmod
# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

eval "$(dircolors ~/.dircolors-solarized)"

# User specific aliases and functions
# found in script in ~/.bashrc.d
