set viminfo='500,<1000,s100,h
set dir=~/tmp/vim
set undodir=~/tmp/vim//
set undofile

set nocompatible
set nofoldenable
set modeline
set modelines=5
set number
let mapleader=','
set incsearch
set showmatch
set hlsearch
set gdefault

nnoremap <leader><space> :noh<cr>
nnoremap <tab> %
vnoremap <tab> %

nnoremap <leader>, ^
vnoremap <leader>, ^
nnoremap <leader>. $
vnoremap <leader>. $

nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>

nnoremap	<leader>R q
inoremap  <leader>R q

nnoremap q <nop>
vnoremap q <nop>

nnoremap ; :

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab 

"highligh matching brackets
set showmatch
set backspace=indent,eol,start
set autoindent

"single tap in, double tap out
vnoremap vv  <Esc><Esc>
inoremap ii  <Esc><Esc>

map j gj
map k gk

set nospell
set wrap
set linebreak

execute pathogen#infect()

"rainbow parenthese"
let g:rainbow_active=1
"integration with tmux
hi statusline ctermfg=234
hi statusline ctermbg=241

let g:NeatStatusLine_color_normal='ctermfg=234 ctermbg=50'
let g:NeatStatusLine_color_insert='ctermfg=234 ctermbg=199'
let g:NeatStatusLine_color_replace='ctermfg=234 ctermbg=130'
let g:NeatStatusLine_color_visual='ctermfg=234 ctermbg=148'

let g:NeatStatusLine_color_position='ctermfg=233 ctermbg=241'
let g:NeatStatusLine_color_line='ctermfg=233 ctermbg=241'
let g:NeatStatusLine_color_modified='ctermfg=234 ctermbg=50'
let g:NeatStatusLine_color_filetype='ctermfg=233 ctermbg=241'

syntax enable
set t_Co=256
set background=dark
colorscheme solarized

autocmd BufRead,BufNewFile *.cu set filetype=cpp
autocmd BufRead,BufNewFile *.pig set filetype=pig syntax=pig
autocmd BufRead,BufNewFile *.soy set filetype=soy syntax=soy.html
autocmd BufRead,BufNewFile *.hb set filetype=handlebars syntax=handlebars.html
autocmd FileType make setlocal noexpandtab

autocmd FileType scss  setlocal tabstop=2
autocmd FileType scss  setlocal shiftwidth=2
autocmd FileType scss  setlocal softtabstop=2

autocmd FileType javascript  setlocal tabstop=2
autocmd FileType javascript  setlocal shiftwidth=2
autocmd FileType javascript  setlocal softtabstop=2

autocmd FileType typescript  setlocal tabstop=2
autocmd FileType typescript  setlocal shiftwidth=2
autocmd FileType typescript  setlocal softtabstop=2

autocmd FileType vue  setlocal tabstop=2
autocmd FileType vue  setlocal shiftwidth=2
autocmd FileType vue  setlocal softtabstop=2

autocmd FileType yaml  setlocal tabstop=2
autocmd FileType yaml  setlocal shiftwidth=2
autocmd FileType yaml  setlocal softtabstop=2

autocmd FileType tf setlocal tabstop=2
autocmd FileType tf setlocal shiftwidth=2
autocmd FileType tf setlocal softtabstop=2

autocmd FileType go setlocal noexpandtab
let g:syntastic_cpp_compiler_options="-std=c++11"

function Focus_on()
    colorscheme seoul256
    Goyo
    Limelight
endfunction

function Focus_off()
    Goyo!
    Limelight!
    set background=dark
    colorscheme solarized 
endfunction

let g:Focus_is_on=0

function Focus_toggle()
    if g:Focus_is_on
        call Focus_off()
        let g:Focus_is_on=0
    else
        call Focus_on()
        let g:Focus_is_on=1
    endif
endfunction

nnoremap <leader>f :call Focus_toggle()<cr>

set pastetoggle=<leader>p 
set re=0

let g:coc_global_extension = ['coc-tsserver']
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif
if has("nvim-0.5.0") || has("patch-8.1.1564")
  " Recently vim can merge signcolumn and number column into one
  set signcolumn=number
else
  set signcolumn=yes
endif


" use <tab> for trigger completion and navigate to the next complete item
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction

inoremap <silent><expr> <Tab>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<Tab>" :
      \ coc#refresh()

inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
" C-o goes back

nmap <silent> ld :CocList diagnostics<CR>
autocmd BufNewFile,BufRead *.pkr.hcl set filetype=hcl


call plug#begin()
Plug 'nvim-tree/nvim-web-devicons' " optional
Plug 'nvim-tree/nvim-tree.lua'

call plug#end()
